name: Java

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B package --file pom.xml -DskipTests
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Build File
        path: target/*.jar

  unit_tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'oracle'
        java-version: '17'
        cache: 'maven'
    - name: Run Tests
      run: mvn test