name: Terraform

on:
  pull_request:
    branches: ["terraform"]
  workflow_dispatch:
    inputs:
      run_apply:
        description: "Run Terraform Apply"
        required: true
        default: "false"
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform_plan:
    name: Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Terraform 1.6.6 version
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
      - name: Terraform Format
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
      - name: Terraform Init
        id: init
        run: terraform init
      - name: Terraform Validate
        id: validate
        run: terraform validate
      - name: Terraform Plan
        id: plan
        if: github.event_name == 'pull_request'
        run: terraform plan -input=false -compact-warnings -var="environment=dev" -out=planfile
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Planfile
          path: planfile

  terraform_apply:
    name: Plan
    runs-on: ubuntu-latest
    environment: dev-manual
    needs: terraform_plan
    defaults:
      run:
        working-directory: terraform
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Planfile
      - name: Use Terraform 1.6.6 version
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
