name: Terraform

on:
  pull_request:
    branches: [ "terraform" ]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: "us-east-1"

jobs:
  terraform:
    name: Plan / Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    permissions:
      contents: read
      pull-requests: write
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Use Terraform 1.6.6 version
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.6
